### ISSUE TITLE
Error displaying "Job" table under consumer database

### ISSUE THREAD

**Issue by mohanbaabu1996** [databrickslabs/overwatch#323]
Attaching the full error message:

SparkException: Cannot recognize hive type string: struct<email_notifications:struct<no_alert_for_skipped_runs:boolean,on_failure:array<string>,on_start:array<string>,on_success:array<string>>,libraries:array<struct<jar:string,maven:struct<coordinates:string>,cran:struct<package:string,repo:string>,pypi:struct<package:string>,whl:string>>,notebook_task:struct<base_parameters:map<string,string>,notebook_path:string>,schedule:struct<pause_status:string,quartz_cron_expression:string,timezone_id:string>,spark_jar_task:struct<jar_uri:string,main_class_name:string,parameters:array<string>,bypass_jar_validation:boolean,run_as_repl:boolean>,format:string,max_retries:bigint,min_retry_interval_millis:bigint,pipeline_task:struct<pipeline_id:string>,python_wheel_task:struct<entry_point:string,package_name:string,parameters:array<string>>,retry_on_timeout:boolean,spark_python_task:struct<parameters:array<string>,python_file:string>,spark_submit_task:struct<parameters:array<string>>,tasks:array<struct<depends_on:array<struct<task_key:string>>,description:string,email_notifications:struct<no_alert_for_skipped_runs:boolean,on_failure:array<string>,on_start:array<string>,on_success:array<string>>,existing_cluster_id:string,libraries:array<struct<jar:string,maven:struct<coordinates:string>,whl:string,cran:struct<package:string>>>,max_retries:bigint,min_retry_interval_millis:bigint,new_cluster:struct<autoscale:struct<max_workers:bigint,min_workers:bigint>,autotermination_minutes:bigint,aws_attributes:map<string,string>,cluster_log_conf:struct<dbfs:struct<destination:string>>,cluster_name:string,custom_tags:map<string,string>,driver_node_type_id:string,enable_elastic_disk:boolean,init_scripts:array<struct<dbfs:struct<destination:string>>>,instance_pool_id:string,node_type_id:string,num_workers:bigint,policy_id:string,spark_conf:map<string,string>,spark_env_vars:map<string,string>,spark_version:string,azure_attributes:map<string,string>,driver_instance_pool_id:string,enable_local_disk_encryption:boolean>,notebook_task:struct<base_parameters:map<string,string>,notebook_path:string>,pipeline_task:struct<pipeline_id:string>,retry_on_timeout:boolean,spark_jar_task:struct<jar_uri:string,main_class_name:string,parameters:array<string>>,spark_python_task:struct<parameters:array<string>,python_file:string>,spark_submit_task:struct<parameters:array<string>>,task_key:string,timeout_seconds:bigint,job_cluster_key:string>>,existing_cluster_id:string,max_concurrent_runs:bigint,name:string,new_cluster:struct<azure_attributes:map<string,string>,cluster_log_conf:struct<dbfs:struct<destination:string>>,custom_tags:map<string,string>,init_scripts:array<struct<dbfs:struct<destination:string>>>,spark_conf:map<string,string>,spark_env_vars:map<string,string>,autotermination_minutes:bigint,aws_attributes:map<string,string>,cluster_source:string,enable_local_disk_encryption:boolean,docker_image:struct<url:string>,autoscale:struct<max_workers:bigint,min_workers:bigint>,cluster_name:string,driver_instance_pool_id:string,driver_node_type_id:string,enable_elastic_disk:boolean,instance_pool_id:string,node_type_id:string,num_workers:bigint,spark_version:string,policy_id:string>,timeout_seconds:bigint,job_clusters:array<struct<job_cluster_key:string,new_cluster:struct<aws_attributes:struct<availability:string,ebs_volume_count:bigint,ebs_volume_size:bigint,ebs_volume_type:string,first_on_demand:bigint,spot_bid_price_percent:bigint,zone_id:string>,cluster_name:string,enable_elastic_disk:boolean,node_type_id:string,num_workers:bigint,policy_id:string,spark_env_vars:struct<PYSPARK_PYTHON:string>,spark_version:string,azure_attributes:struct<availability:string,first_on_demand:bigint,spot_bid_max_price:double>,custom_tags:struct<ResourceClass:string>,spark_conf:struct<spark_databricks_cluster_profile:string,spark_databricks_delta_preview_enabled:string,spark_master:string,spark_databricks_delta_merge_enableLowShuffle:string>,cluster_log_conf:struct<dbfs:struct<destination:string>>,driver_instance_pool_id:string,driver_node_type_id:s, column: new_settings, db: overwatch_global, table: job

**Comment by GeekSheikh** [comment]
Providing an update here -- Databricks engineering is investigating the issue and we'll provide a work around or fix ASAP

**Comment by GeekSheikh** [comment]
Caused by #339 -- intermediate resolution still pending but should be ready week of 4/4/2022.

0605 should address the underlying issue

**Comment by GeekSheikh** [comment]
will be permanently resolved in 0605. The issue comes from new fields being pushed from Databricks due to new features causing schema size explosion. Will update with final repair steps in 0605 release docs

**Comment by GeekSheikh** [comment]
**Root Cause**: Databricks began publishing new fields as part of some of the new jobs features and these fields were causing the schema to get too large to display.

**Resolution**: Upgrade to Overwatch 0605+ and complete at least one run. After the run try to drop the view `overwatch.job`. If you receive an error when trying to drop the view, please file a support ticket with the verbiage below in it. Once the ticket is complete, you may drop the view and it will be recreated during the next Overwatch run. You may also recreate the view with the following function. ```Gold(workspace).refreshViews()```

**Note**: if you do not upgrade to 0605+ first, you may continue to hit the issue or hit it again in the near future.

**Ticket Verbiage**:
Please raise the typeName limit for <DATABASE>.job to 8000 in our HMS DB for workspace id <WORKSPACEID>. Full error message is below <PASTE FULL ERROR TEXT FROM drop view statement>

**Comment by ThomasDAdams** [comment]
Hi @GeekSheikh I am still getting this exact same issue on v0.6.1.0. Is there anything you would recommend I do to fix it?

**Comment by GeekSheikh** [comment]
@ThomasDAdams -- did you submit the ticket and extend the typename in the metastore? This is not something that will be fixed by simply upgrading the OW version, this is a metastore default limitation -- Databricks has recently increased this field to 20,000 by default but any metastores created before September likely have the old default of 4000
