### ISSUE TITLE
Regarding DBU cost issue & DBU cost by each user

### ISSUE THREAD

**Issue by NishchayAgarwal** [databrickslabs/overwatch#645]
Hey,
Hope you are doing well
**Issue 1** As I am using verbose audit logging notebook to get DBU cost for each command level. But I am getting incorrect cost as I saw in the formula for calculating DBU cost is wrong  ('uptime_in_state_H / 'total_cost / 60 / 60 / 1000).alias("totalCostPMS") / can you please check whether is correct or not 

**Issue **2**** As I am going to calculate DBU cost for each users for given day, I am going to join spark_job table with clusterstatefact table I am getting incorrect DBU cost because as I saw on today'date my user runs 7 notebooks which redirects cost of 7 notebook commands run on cluster but only 1 notebook is coming in spark job which is incorrect because actual number of notebooks running by user is 7 not 4. Also in sparkjob table, I am getting 8 users information for date 2022-11-29 but actual users are running cluster for same date are 15 
**so I am not able to get DBU cost spend by each user on given day. Can you please help here to resolve data issue on SparkJob table & queries to get DBU cost for each user** 

**Need  DBU cost coming from overwatch for cluster is not matching with actual DBU cost showing in account console**

**Comment by mohanbaabu1996** [comment]
@NishchayAgarwal Could you please provide list of all issues in a high level

**Comment by NishchayAgarwal** [comment]
Hey,
Hope you are doing well

**Issue 1:** Not able to get DBU cost spent by each user on databricks cluster for given day using below query suggested by @mohanbaabu1996 
select date,user_email,b.cluster_id, sum(total_cost)as total_cost from overwatch.clusterstatefact_final a inner join overwatch_etl.sparkjob_gold b on a.cluster_id= b.cluster_id  where a.cluster_id='0712-122411-g7lkrxin' group by date,user_email,b.cluster_id
Because in sparkjob, all notebook that is running by user on given day are coming less than actual notebooks running by user
**so I am not able to get DBU cost spend by each user on given day. Can you please help here to resolve data issue on SparkJob table & queries to get DBU cost for each user on given day**

**Issue 2:** As I am using verbose audit logging notebook to get total estimated cost for each command but in notebook shared by @mohanbaabu1996 , I saw in the formula for calculating DBU cost is wrong ('uptime_in_state_H / 'total_cost / 60 / 60 / 1000).alias("totalCostPMS") / can you please check whether is correct or not
because according to me formula should be different to get DBU cost for command

**Issue 3:** In notebook table some notebook name & notebook path is coming null but notebook id is coming correct (Still notebook exists on databricks). Can you help here to resolve data notebook path & notebook null issue

**Issue 4:** DBU cost coming for All Purpose & Job cluster which is calculated using below command
%sql
with cluster_cost as(
select a.*,  case when is_automated = 'true' and cluster_type not in ('Serverless','SQL Analytics','Single Node') then 'Automated'
                  when is_automated = 'false' and cluster_type not in ('Serverless','SQL Analytics','Single Node') then 'Interactive'
                  when (is_automated = 'false' or is_automated = 'true' or is_automated is null) and cluster_type = 'SQL Analytics' then 'SQL-Warehouse' 
                  when (is_automated = 'false' or is_automated = 'true' or is_automated is null) and cluster_type = 'Serverless' then 'Serverless'
                  when (is_automated = 'false' or is_automated = 'true' or is_automated is null) and cluster_type = 'Single Node' then 'Single Node'
                  else "other" end as cluster_category from  overwatch.clusterstatefact_stats_finalclusterstatefact_stats_final a inner join overwatch.cluster_stats_final b on a.cluster_id=b.cluster_id)
                  select workspace_name,cluster_category, state_start_date,sum(total_DBU_cost) as total_DBU_cost, sum(total_driver_cost) as total_driver_cost, sum(total_worker_cost) as total_worker_cost, sum(total_compute_cost)as total_compute_cost, sum(total_cost) as total_cost  from cluster_cost group by workspace_name,cluster_category, state_start_date

Cost coming from clusterstatefact is coming incorrect as I am matching actual cost with account console databricks cluster costing with above query data output
Can you please help on resolving data discrepancies issues on databricks cluster costing for given day which should match with actual cost showing on Databricks Account Console 

**Issue 5:** Not able to get DBU cost for SQL Endpoint cluster for all cluster. Example, as we are using three SQL Endpoint clusters, for one day all three cluster costing is coming but for another day, only one cluster costing is coming. (Still all three clusters are running on each day)


**Issue 6:** Is there any formula to calculate DBU cost  for each Sql query running by each user using SQL endpoint cluster cost & execution time taken by each query 

I am highly obliged to you if you can help on above issues.
Thanks,

**Comment by GeekSheikh** [comment]
@NishchayAgarwal -- thank you from developer team, we're going to take a look. Thanks for your patience.

**Comment by GeekSheikh** [comment]
I didn't get to this today, apologies. It's at the top of my list to review tomorrow.

**Comment by GeekSheikh** [comment]
@NishchayAgarwal I have addressed all your concerns in a notebook in your environment under the Databricks_Support folder, the notebook is named `Issue_645_Review`. Furthermore, @mohanbaabu1996 will be reaching out to you to discuss each of the items and help you correct the data on Issue 4.

Great questions, please let us know if you have any follow-up needs.

**Comment by NishchayAgarwal** [comment]
Hey @GeekSheikh 
Appreciate your help
As I already went through Notebook I have couple of doubts regarding issues persisting in issues 1,2 & 3 as after applying same conditions & properties, getting incorrect
Can we please connect on same 
I am highly obliged to you

**Comment by mohanbaabu1996** [comment]
@GeekSheikh We had a call and doing a fresh deployment to validate the data

**Comment by NishchayAgarwal** [comment]
Hey @GeekSheikh 
Hope you are doing well 
As I had call @mohanbaabu1996 , we validated the data for the same some of the issues has been resolved but still facing some issues and having concerns regarding the same 

**Issue 1: Can you please check whether formula being used to get DBU cost for command level in the verbose audit logging notebook shared b**y @mohanbaabu1996  in cell number 1 
('uptime_in_state_H / 'total_cost / 60 / 60 / 1000).alias("totalCostPMS") because according to me, formula should be tota_cost divided by uptime can you please verify in notebook attached
[verbose.txt](https://github.com/databrickslabs/overwatch/files/10185071/verbose.txt)

Issue 2: As you mentioned for getting notebook_name not null, I have to lookupwhen function, But when I run this function when overtwach job get completed still getting notebook name & path as null
Can you please tell me how to run this function before or after overwatch job running at daily basis so that no notebook name coming null 

Issue 3: Can you please verify below command is correct or not to get DBU for each user for given day. And What is use meaning of days_in_state can you please give some context as I didn't understand from data dictionary website

```%python
from pyspark.sql.functions import *
clusterstatefact = spark.sql("select * from overwatch_global.clusterstatefact")
sparkjob = spark.sql("select * from overwatch_global.sparkJob")
clusterstatefact_new = clusterstatefact\
.select("organization_id",
        "workspace_name",
        "cluster_id",
        "cluster_name",
        "custom_tags",
        "state",
        "isAutomated",
        "state_dates",
        "days_in_state",
        "total_compute_cost",
        "total_DBU_cost",
        "total_dbus")
sparkjob_new = sparkjob\
.select("organization_id",
        "workspace_name",
        "cluster_id",
        "date",
        "user_email")
clsf = clusterstatefact_new\
.withColumn("Date", explode("state_dates"))
joined_df = clsf\
.join(
  sparkjob_new, (clsf["organization_id"] == sparkjob_new["organization_id"]) &
  (clsf["workspace_name"] == sparkjob_new["workspace_name"]) &
  (clsf["cluster_id"] == sparkjob_new["cluster_id"]) &
  (clsf["Date"] == sparkjob_new["date"]), "inner"
).distinct()
cost_per_user = joined_df\
.groupBy(clsf["organization_id"],
         clsf["workspace_name"],
         clsf["cluster_id"],
         clsf["cluster_name"],
         clsf["days_in_state"],
         clsf["Date"],
         "user_email")\
.agg(round(sum(col("total_compute_cost"))/col("days_in_state"),2).alias("total_compute_cost"),
     round(sum(col("total_dbus"))/col("days_in_state"),2).alias("total_dbus")
    )\
.orderBy(clsf["Date"].desc())\
.distinct()
display(cost_per_user)
cost_per_user.write.format("delta").mode("overwrite").saveAsTable("overwatch_global.cluster_cost_per_user")


**Concern 1:  Can you please share me sample formula to get DBU for each query of DBSQL that you mentioned in notebook issue 6 
Concern 2: Can you please tell me is total dbu cost includes VM cost or only number of DBU spend with SKU multiplication ?**
I am highly obliged to you

**Comment by mohanbaabu1996** [comment]
@NishchayAgarwal Concern 2: Cost functions are explained in the [docs](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#cost-functions-explained)

Kindly have a look into the [code
](https://github.com/databrickslabs/overwatch/blob/main/src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala)

```val driverDBUs = when('databricks_billable, $"driverSpecs.Hourly_DBUs" * 'uptime_in_state_H).otherwise(lit(0)).alias("driver_dbus")

val workerDBUs = when('databricks_billable, $"workerSpecs.Hourly_DBUs" * 'current_num_workers * 'uptime_in_state_H).otherwise(lit(0)).alias("worker_dbus")

val driverComputeCost = Costs.compute('cloud_billable, $"driverSpecs.Compute_Contract_Price", lit(1), 'uptime_in_state_H).alias("driver_compute_cost")

val workerComputeCost = Costs.compute('cloud_billable, $"workerSpecs.Compute_Contract_Price", 'target_num_workers, 'uptime_in_state_H).alias("worker_compute_cost")

val driverDBUCost = Costs.dbu('databricks_billable, $"driverSpecs.Hourly_DBUs", 'dbu_rate, lit(1), 'uptime_in_state_H, runtimeEngine = 'runtime_engine, sku = 'sku).alias("driver_dbu_cost")

val workerDBUCost = Costs.dbu('databricks_billable, $"workerSpecs.Hourly_DBUs", 'dbu_rate, 'current_num_workers, 'uptime_in_state_H, runtimeEngine = 'runtime_engine, sku = 'sku).alias("worker_dbu_cost")```

**Comment by NishchayAgarwal** [comment]
sure @mohanbaabu1996
Can you please help  me with other issues or concerns

**Comment by NishchayAgarwal** [comment]
Hey @GeekSheikh
Hope you are doing well
As I had call @mohanbaabu1996 , we validated the data for the same some of the issues has been resolved but still facing some issues and having concerns regarding the same

Issue 1: Can you please check whether formula being used to get DBU cost for command level in the verbose audit logging notebook shared by @mohanbaabu1996 in cell number 1
('uptime_in_state_H / 'total_cost / 60 / 60 / 1000).alias("totalCostPMS") because according to me, formula should be tota_cost divided by uptime can you please verify in notebook attached
[verbose.txt](https://github.com/databrickslabs/overwatch/files/10185071/verbose.txt)

Issue 2: As you mentioned for getting notebook_name not null, I have to lookupwhen function, But when I run this function when overtwach job get completed still getting notebook name & path as null
Can you please tell me how to run this function before or after overwatch job running at daily basis so that no notebook name coming null

Issue 3: Can you please verify below command is correct or not to get DBU for each user for given day. And What is use meaning of days_in_state can you please give some context as I didn't understand from data dictionary website

from pyspark.sql.functions import *
clusterstatefact = spark.sql("select * from overwatch_global.clusterstatefact")
sparkjob = spark.sql("select * from overwatch_global.sparkJob")
clusterstatefact_new = clusterstatefact\
.select("organization_id",
        "workspace_name",
        "cluster_id",
        "cluster_name",
        "custom_tags",
        "state",
        "isAutomated",
        "state_dates",
        "days_in_state",
        "total_compute_cost",
        "total_DBU_cost",
        "total_dbus")
sparkjob_new = sparkjob\
.select("organization_id",
        "workspace_name",
        "cluster_id",
        "date",
        "user_email")
clsf = clusterstatefact_new\
.withColumn("Date", explode("state_dates"))
joined_df = clsf\
.join(
  sparkjob_new, (clsf["organization_id"] == sparkjob_new["organization_id"]) &
  (clsf["workspace_name"] == sparkjob_new["workspace_name"]) &
  (clsf["cluster_id"] == sparkjob_new["cluster_id"]) &
  (clsf["Date"] == sparkjob_new["date"]), "inner"
).distinct()
cost_per_user = joined_df\
.groupBy(clsf["organization_id"],
         clsf["workspace_name"],
         clsf["cluster_id"],
         clsf["cluster_name"],
         clsf["days_in_state"],
         clsf["Date"],
         "user_email")\
.agg(round(sum(col("total_compute_cost"))/col("days_in_state"),2).alias("total_compute_cost"),
     round(sum(col("total_dbus"))/col("days_in_state"),2).alias("total_dbus")
    )\
.orderBy(clsf["Date"].desc())\
.distinct()
display(cost_per_user)
cost_per_user.write.format("delta").mode("overwrite").saveAsTable("overwatch_global.cluster_cost_per_user")


**Concern 1:  Can you please share me sample formula to get DBU for each query of DBSQL that you mentioned in notebook issue 6 
Concern 2: why we need VM cost details in calculating DBU cost is it necessary just wanted to confirm ?**
I am highly obliged to you

**Comment by NishchayAgarwal** [comment]
Any update on this @mohanbaabu1996 @GeekSheikh 
I am highly obliged to you if you can look https://github.com/databrickslabs/overwatch/issues/645#issuecomment-1343087188

**Comment by mohanbaabu1996** [comment]
@NishchayAgarwal

Issue 1 -  As already mentioned in the notebook, change the _total_cost_ to _total_dbus_
Issue 2 - Can you share with us the notebook where you performed the [function](https://databrickslabs.github.io/overwatch/gettingstarted/advancedtopics/#joining-with-slow-changing-dimensions-scd)

![image](https://user-images.githubusercontent.com/87074323/207575185-7f5b72d7-3447-4e8e-add1-d5286ba76c77.png)

Concern 1 - Have you tried any query based on the hint given in issue 6 ? If yes, please share will review it.
Concern 2 - Yes, it is required. Actually we need specifically hourly DBUs value for calculating DBU cost

**Comment by NishchayAgarwal** [comment]
Hey @mohanbaabu1996  
For the issue 1 :
I have concern about the formula being used in verbose audit logging notebook that u shared is correct or not
notebook shared by @mohanbaabu1996 in cell number 1
('uptime_in_state_H / 'total_cost / 60 / 60 / 1000).alias("totalCostPMS") because according to me, formula should be tota_cost divided by uptime can you please verify in notebook attached

For Issue 2:
As @GeekSheikh  mentioned for getting notebook_name not null, I have to lookupwhen function, But when I run this function when overtwach job get completed still getting notebook name & path as null
Can you please tell me how to run this lookup when functions before or after overwatch job running at daily basis so that no notebook name coming null

For Issue 3:
Issue 3: Can you please verify below command is correct or not to get DBU for each user for given day. And What is use meaning of days_in_state can you please give some context as I didn't understand from data dictionary website

from pyspark.sql.functions import *
clusterstatefact = spark.sql("select * from overwatch_global.clusterstatefact")
sparkjob = spark.sql("select * from overwatch_global.sparkJob")
clusterstatefact_new = clusterstatefact
.select("organization_id",
"workspace_name",
"cluster_id",
"cluster_name",
"custom_tags",
"state",
"isAutomated",
"state_dates",
"days_in_state",
"total_compute_cost",
"total_DBU_cost",
"total_dbus")
sparkjob_new = sparkjob
.select("organization_id",
"workspace_name",
"cluster_id",
"date",
"user_email")
clsf = clusterstatefact_new
.withColumn("Date", explode("state_dates"))
joined_df = clsf
.join(
sparkjob_new, (clsf["organization_id"] == sparkjob_new["organization_id"]) &
(clsf["workspace_name"] == sparkjob_new["workspace_name"]) &
(clsf["cluster_id"] == sparkjob_new["cluster_id"]) &
(clsf["Date"] == sparkjob_new["date"]), "inner"
).distinct()
cost_per_user = joined_df
.groupBy(clsf["organization_id"],
clsf["workspace_name"],
clsf["cluster_id"],
clsf["cluster_name"],
clsf["days_in_state"],
clsf["Date"],
"user_email")
.agg(round(sum(col("total_compute_cost"))/col("days_in_state"),2).alias("total_compute_cost"),
round(sum(col("total_dbus"))/col("days_in_state"),2).alias("total_dbus")
)
.orderBy(clsf["Date"].desc())
.distinct()
display(cost_per_user)
cost_per_user.write.format("delta").mode("overwrite").saveAsTable("overwatch_global.cluster_cost_per_user")


we can connect on the same @mohanbaabu1996  as we had connected on the same i showed u above issues or we can connect again on the same

**Comment by mohanbaabu1996** [comment]
@NishchayAgarwal 
Issue 1: You're right, uptime_in_state_H  should be in the denominator
Issue 2 : I've shared the notebook, please have a look

**Comment by NishchayAgarwal** [comment]
Hey @mohanbaabu1996
**For the issue 1 :**
I have concern about the formula being used in verbose audit logging notebook that u shared is correct or not
notebook shared by @mohanbaabu1996 in cell number 1
('total_dbus / 'uptime / 60 / 60 / 1000).alias("totalCostPMS") because according to me, formula should not divided by 1000 because execution_time coming in seconds not in msec Can you please verify it because we have to divide only 60*60 not by 60*60*1000

For Issue 2:
As @GeekSheikh mentioned for getting notebook_name not null, I have to lookupwhen function, But when I run this function when overtwach job get completed still getting notebook name & path as null

Also @mohanbaabu1996  shared me notebook but still I am getting notebook_name & notebook_path as null I run this notebook after daily overwatch job get completed 
Below is the notebook
[notebook_null.txt](https://github.com/databrickslabs/overwatch/files/10286359/notebook_null.txt)


For Issue 3:
Issue 3: Can you please verify final notebook to get DBU for each user for given day. 
@mohanbaabu1996  shared me notebook for getting DBU cost for each cluster on each day but this notebook was not applicable for cluster costing for each users for each day can u share me updated command to get DBU cost for each user 
I already discussed with @mohanbaabu1996  for the same that I need DBU cost for each user for each  days

**Comment by mohanbaabu1996** [comment]
@NishchayAgarwal I hope you doing well.
We've released few versions like 0710 & 0711, that handles multiple fixes especially DBUs & DBU cost.
Please ping me in slack, when you're available to update.
Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @NishchayAgarwal ,

Please ping me in slack, when you're available to update and discuss further.
Thanks!
